"""delet fk

Revision ID: 04bd54e3d701
Revises: bd7806e35205
Create Date: 2025-06-17 11:48:55.681085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '04bd54e3d701'
down_revision: Union[str, Sequence[str], None] = 'bd7806e35205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invite_links', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('invite_links', 'chat_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('invite_links_ibfk_1'), 'invite_links', type_='foreignkey')
    op.drop_constraint(op.f('invite_links_ibfk_2'), 'invite_links', type_='foreignkey')
    op.drop_index(op.f('username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_foreign_key(op.f('invite_links_ibfk_2'), 'invite_links', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('invite_links_ibfk_1'), 'invite_links', 'chats', ['chat_id'], ['id'])
    op.alter_column('invite_links', 'chat_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('invite_links', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
