"""add broadcasts

Revision ID: 183f7fd95c5d
Revises: ed2cf11b0707
Create Date: 2025-08-20 20:10:32.615775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183f7fd95c5d'
down_revision: Union[str, Sequence[str], None] = 'ed2cf11b0707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.Enum('news', 'meetings', 'important', name='broadcast_kind'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'sending', 'sent', 'failed', name='broadcast_status'), server_default='draft', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_broadcasts_scheduled_at', 'broadcasts', ['scheduled_at'], unique=False)
    op.create_index('ix_broadcasts_status', 'broadcasts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_broadcasts_status', table_name='broadcasts')
    op.drop_index('ix_broadcasts_scheduled_at', table_name='broadcasts')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
