"""Add resours column to links

Revision ID: 53947e263526
Revises: ada14aadae04
Create Date: 2025-06-21 17:32:32.983237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53947e263526'
down_revision: Union[str, Sequence[str], None] = 'ada14aadae04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_invite_user_chat', 'invite_links_chats', ['user_id', 'chat_id'])
    op.add_column('links', sa.Column('resours', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'resours')
    op.drop_constraint('uq_invite_user_chat', 'invite_links_chats', type_='unique')
    # ### end Alembic commands ###
