"""rename_income_to_turnover_in_offers

Revision ID: e2fb640b3e45
Revises: 241244847855
Create Date: 2025-07-09 17:19:09.734199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2fb640b3e45'
down_revision: Union[str, Sequence[str], None] = '241244847855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('turnover', sa.Float(), nullable=False))
    op.drop_column('offers', 'income')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('income', mysql.FLOAT(), nullable=False))
    op.drop_column('offers', 'turnover')
    # ### end Alembic commands ###
