"""Fix resours column to links

Revision ID: ebcff93260a4
Revises: 53947e263526
Create Date: 2025-06-21 17:34:15.482261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ebcff93260a4'
down_revision: Union[str, Sequence[str], None] = '53947e263526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('resource', sa.String(length=255), nullable=True))
    op.drop_column('links', 'resours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('resours', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('links', 'resource')
    # ### end Alembic commands ###
